title: Hattie Chung
url: "https://hattiechung.github.io"
baseurl: "/"

markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass

footer: yes
footer_url: ""
footer_text: "~~~"

nav:
 - name: "About"
   link: "/"
 - name: "CV"
   link: "/pdfs/cv.pdf"
