title: Hattie Chung
url: "https://hattiechung.github.io"
baseurl: "/"

markdown: kramdown

footer_url: ""
footer_text: "~~~"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "/pdfs/cv.pdf"
